### ISSUE TITLE
Selected first item

### ISSUE THREAD

**Issue by BraunTom** [hpi-swa-teaching/ChangesBrowser#102]
If I switch to detailed view I stay in your tool (that is ok) and the first line is selected but nothing is shown on the right side. 
In the old recover changes tool there was still the choose button so this was ok but in your tool it is confusing as the user has to click again on an item to see changes.
Would be nicer to directly show the changes from the first item on the left.

**Comment by marcelgarus** [comment]
This isn't relevant anymore because we soon show a welcome text on startup.
