### ISSUE TITLE
Removed methods

### ISSUE THREAD

**Issue by marcelgarus** [hpi-swa-teaching/ChangesBrowser#104]
Methods that got removed some time ago still appear in the browser because some `ChangeRecord`s reference them, causing `isInImage` to incorrectly return `false`.

One would have to change `isInImage` to return "true" for changes that have been removed from the Image on purpose (or better add another kind of check like `wasDeleted`)

**Comment by marcelgarus** [comment]
This gets especially bad when they get removed because we switched to a different git branch – that causes several methods to still be displayed that happen on another branch.

**Comment by hpistudent72** [comment]
IsInImage isn't used anymore
