### ISSUE TITLE
Write test for correct order of ChangeListItems

### ISSUE THREAD

**Issue by marcelgarus** [hpi-swa-teaching/ChangesBrowser#109]
Write a test that asserts that Chanegs loaded from the Changes File are always chronologically ordered

**Why is that happening?**

Sadly, change timestamps in Squeak work on minute granularity — as mind-boggling as that is, this means that two changes that happened at 12:34 are treated as if they happened in the exact same instant.
Inside the changes file, changes are stored with the newest one at the end. Thus, when retrieving the changes from the file, they are placed in an OrderedCollection with the youngest change at the end. Filtering changes by whether they are in the image doesn't affect the ordering. Because sorting in Smalltalk is stable, changes with the same timestamp remain in the same ordering, even after we reverse-order changes by timestamp.

**What to do about it**

We should probably reverse the collection of changes before (or instead of?) ordering them. This way, the youngest changes are always guaranteed to be at the top.

**Comment by SilvanVerhoeven** [comment]
Fixed in #113
