### ISSUE TITLE
Wrong "legacy" project supported?

### ISSUE THREAD

**Issue by strawberriesandcheese** [hpi-swa-teaching/ChangesBrowser#116]
When you use the "detailed view" button you get to the project from 2017 and not the current Changes Browser. Is this really how it should be?
When I thought about this alone while listening to the presentation it didn't make much sense to me. Especially since that is the one we wanna replace.

**Comment by SilvanVerhoeven** [comment]
Ask Patrick first

**Comment by hpistudent72** [comment]
What happened to this? @strawberriesandcheese, @SilvanVerhoeven, @marcelgarus did you get an answer?

**Comment by MarcelGarus** [comment]
It's a long time ago, but I believe that was the right behavior. The browser from 2017 has a very straightforward-to-use design simply showing the list of changes, so it's actually less confusing than the tool developed before our year. AFAIK Patrick still uses the browser from 2017 anyway, so we link back directly to this tried-and-tested tool.

(So, I believe this issue can be closed)
