### ISSUE TITLE
32 - Aktiver Filter

### ISSUE THREAD

**Issue by MaxHaubold** [hpi-swa-teaching/ChangesBrowser#12]
Ich möchte den aktuell aktiven Filter hervorgehoben sehen, um zu wissen, welcher Filter verwendet wird.

**Comment by MarvinThiele** [comment]
Der Filter ist so geschrieben, dass man anscheinend mehrere Sachen gleichzeitig aktiv haben kann. Also z.B. wenn man Method auswählt dann kommen Methods. Super. Wenn man dann class comments auswählt kommt nichts. Auch gut. Wenn man dann allerdings wieder auf class comments clickt, kommen nur methods. WTF.

**Comment by MarvinThiele** [comment]
Aktueller Filter steht in der instance variable filterMode von CHBrowserLogic

**Comment by MarvinThiele** [comment]
FilterPairs im CHBrower anpassen

**Comment by MarvinThiele** [comment]
Checked an menuSpec senden bzw speichern
