### ISSUE TITLE
Format overridden changes

### ISSUE THREAD

**Issue by SilvanVerhoeven** [hpi-swa-teaching/ChangesBrowser#120]
As a developer, I want to see which changes are overridden by newer picked changes in order to understand which changes will be loaded and which won't be loaded and why.

**Acceptance criteria**

- [ ] grey out changes overridden by newer changes
- [ ] overridden changes are (as of now) not (un)pickable --> disable pick button

**Comment by hpistudent72** [comment]
Solved by grouping changes on the same method/class comment
