### ISSUE TITLE
Changes are accidentally seen as being in the image because of timestamp

### ISSUE THREAD

**Issue by gritfessel** [hpi-swa-teaching/ChangesBrowser#125]
When changes have been made to the same method within the same minute, and an earlier one of those changes gets loaded into the image, all of the other changes made to that method within the same minute disappear from the change list, too. That is because of the problem already addressed in #109, that timestamps in Squeak work on minute granularity. In `ChangeRecord>>isInImage` we check for the timestamp of the method that is currently in the image to be greater **or equal** than the timestamp of the change we check at that moment. Actually different changes cannot be seen as different like that.

**Comment by hpistudent72** [comment]
IsInImage isn't used anymore.
