### ISSUE TITLE
64 - Fehlermeldung: fehlende Klasse

### ISSUE THREAD

**Issue by MaxHaubold** [hpi-swa-teaching/ChangesBrowser#14]
Wenn Changes in eine nicht existierende Klasse hinein-recovert werden sollen, möchte ich eine Möglichkeit bekommen diese Klasse zu erstellen, um den Recovervorgang ungestört fortsetzen zu können.

**Comment by conradlempert** [comment]
Soll automatisch die Klasse erstellen und von Object erben
