### ISSUE TITLE
64 - Löschen von neuen Klassen

### ISSUE THREAD

**Issue by conradlempert** [hpi-swa-teaching/ChangesBrowser#19]
Erstelle eine Klasse im aktuellen Snapshot, füge eine Methode hinzu, lösche diese Klasse -> Absturz

**Comment by MaxHaubold** [comment]
Ich möchte im aktuellen Snapshot eine neue Klasse erstellen können, zu ihr eine Methode hinzufügen, und dann recovern ohne abzustürzen, um das RecoverChanges Tool auch in diesem Use-Case benutzen zu können.
