### ISSUE TITLE
Only show the last state of a method

### ISSUE THREAD

**Issue by marcelgarus** [hpi-swa-teaching/ChangesBrowser#51]
As a developer, I want to see only the last state of a method, because older changes are not that relevant to me.

**Acceptance criteria:**

- [x] In the main list, there’s only one entry per method.
- [x] For every entry, a description of the latest change is shown as well as a timestamp of when it happened.
- [x] The entries are in chronological order from the latest to the oldest change.

**Comment by hpistudent72** [comment]
Conflicts with grouping
