### ISSUE TITLE
Show the changes made to method's source code

### ISSUE THREAD

**Issue by marcelgarus** [hpi-swa-teaching/ChangesBrowser#53]
As a developer, I want to compare the method’s source code from before the selected change to the code with the selected change applied, because I want to understand for sure the effect the selected change has on the code.

**Acceptance criteria:**

- [x] There is a box underneath both lists, showing the complete code of the selected method.
- [ ] Additional code from the selected change is green, the removed code is red and struck through.

**Comment by hpistudent72** [comment]
Instead of always using red/green, we used Squeak-Style differences (colors adapt to chosen theme).
