### ISSUE TITLE
isInImage gives wrong result

### ISSUE THREAD

**Issue by SilvanVerhoeven** [hpi-swa-teaching/ChangesBrowser#79]
Currently, isInImage compares only the source code of methods. This is clearly wrong as older changes that are in the image, but got overwritten by newer changes, are considered as not being in the image.
Instead of the source code, we should judge changes based on their timestamps.

**Acceptance criteria:**

- [x] Move function to ChangeRecord extension.
- isInImage works properly for
  - [x] methods
  - [x] class comments
  - do-its
    - [ ] class creations
    - [ ] class deletion
    - [ ] method deletion
    - [ ] category renames
    - [ ] instance variable creation
    - [ ] instance variable deletion
    - [ ] class variable creation
    - [ ] class variable deletion
    - [ ] method reclassifications

**Comment by marcelgarus** [comment]
Also move CRChangeList>>modifiesClass: to ChangeRecord

**Comment by gritfessel** [comment]
How is it going? We have problems with the testing stuff due to this function not working how it is intended.

**Comment by marcelgarus** [comment]
@gritfessel See issue description for updates

**Comment by hpistudent72** [comment]
Changed logic for choosing changes (now based on last open, handled by CRSessionState).
