### ISSUE TITLE
Chronological view

### ISSUE THREAD

**Issue by marcelgarus** [hpi-swa-teaching/ChangesBrowser#99]
As a developer, I want to see all the changes in chronological order because this is what most users expect.

**Acceptance criteria**

- [x] There is only one big chronological list of all changes.
- [x] By default, all changes are selected.
- [ ] Show a welcome text in the code pane to tell users they can exclude changes that should not be loaded into the image.
- [ ] Excluded changes are struck through or in parenthesis or greyed out or multiple of these.
- [ ] Underneath the list and above the code pane, there's a button bar with the following buttons:
  - [x] If change included: "Exclude this change" for excluding the currently selected change from being loaded.
  - [x] If change excluded: "Include this change" for including the currently selected change into the list of changes being loaded.
  - [ ] When excluding a change, the change below the one just excluded is selected.

**Comment by hpistudent72** [comment]
https://github.com/hpi-swa-teaching/ChangesBrowser/pull/158 Conflicts with the last task.
